name: Build PS2 Launcher PKG

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env vars
        run: |
          echo "OO_PS4_TOOLCHAIN=${GITHUB_WORKSPACE}/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

      - name: Cache OpenOrbis Toolchain
        id: cache-oosdk
        uses: actions/cache@v4
        with:
          path: ${{ env.OO_PS4_TOOLCHAIN }}
          key: ${{ runner.os }}-oosdk-illusion

      - name: Download OpenOrbis Toolchain
        if: steps.cache-oosdk.outputs.cache-hit != 'true'
        run: |
          curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/0.0.1.416/toolchain.tar.gz | tar xz -C ./

      - name: Checkout oosdk_libraries
        uses: actions/checkout@v4
        with:
          repository: bucanero/oosdk_libraries
          path: oosdk_libraries

      - name: Copy makerules
        run: cp oosdk_libraries/build_rules.mk OpenOrbis/PS4Toolchain/build_rules.mk

      - name: Checkout libjbc
        uses: actions/checkout@v4
        with:
          repository: bucanero/ps4-libjbc
          path: ps4-libjbc

      - name: Install libjbc
        working-directory: ps4-libjbc
        run: make AR=ar install

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0"

      - name: Build PKG
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps2-launcher
          path: "*.pkg"
